Repository mikhail-nechaev/technopolis_aads_2018, pull requests merged in 2018-12, with the labels that each got.

#2 Data structure
  src/ru/mail/polis/collections/iterator/todo/IntegerIncreasingSequencePeekingIterator.java
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/hash/todo/OpenHashTable.java
  src/ru/mail/polis/collections/set/hash/todo/Student.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTree.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTreeIterable.java
  src/ru/mail/polis/collections/set/sorted/todo/RedBlackTree.java
  src/ru/mail/polis/collections/set/sorted/todo/RedBlackTreeIterable.java
Labels: t15_oht, t8_apqsr

#17 1 part
  src/Main.java
  src/ru/mail/polis/collections/iterator/todo/IntegerIncreasingSequencePeekingIterator.java
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/list/123
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/hash/todo/OpenHashTable.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTree.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTreeIterable.java
  src/ru/mail/polis/collections/set/sorted/todo/RedBlackTree.java
Labels: listIt

#19 Homework - part 1
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  test/ru/mail/polis/collections/custom/Stub.java
Labels: listIt

#37 iterator + list + hash
  src/ru/mail/polis/collections/iterator/todo/IntegerIncreasingSequencePeekingIterator.java
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/hash/todo/OpenHashTable.java
  src/ru/mail/polis/collections/set/hash/todo/Student.java
Labels: duplicate

#34 AVLI remove
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTreeIterable.java
Labels: invalid

#30 first commit
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/hash/todo/OpenHashTable.java
  src/ru/mail/polis/collections/set/hash/todo/Student.java
Labels: invalid

#52 Шахов, Правильный PR (код тот же, дедлайн не учитывается)
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
Labels: listIt

#44 Homework Nosov
  README.md
  src/ru/mail/polis/collections/iterator/todo/IntegerIncreasingSequencePeekingIterator.java
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTree.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTreeIterable.java
Labels: duplicate

#24 Tasks Done
  src/ru/mail/polis/collections/iterator/todo/IntegerIncreasingSequencePeekingIterator.java
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/hash/todo/Student.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTree.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTreeIterable.java
  src/ru/mail/polis/collections/set/sorted/todo/RedBlackTree.java
  test/ru/mail/polis/collections/TestHelper.java
  test/ru/mail/polis/collections/set/AbstractSetTest.java
  test/ru/mail/polis/collections/set/hash/TestHashTable.java
Labels: duplicate, invalid

#45 homework
  README.md
  src/ru/mail/polis/collections/iterator/todo/IntegerIncreasingSequencePeekingIterator.java
  src/ru/mail/polis/collections/iterator/todo/MergingPeekingIncreasingIterator.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeFull.java
  src/ru/mail/polis/collections/list/todo/ArrayDequeSimple.java
  src/ru/mail/polis/collections/list/todo/ArrayPriorityQueueSimple.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeFull.java
  src/ru/mail/polis/collections/list/todo/LinkedDequeSimple.java
  src/ru/mail/polis/collections/set/hash/todo/OpenHashTable.java
  src/ru/mail/polis/collections/set/hash/todo/Student.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTree.java
  src/ru/mail/polis/collections/set/sorted/todo/AVLTreeIterable.java
  src/ru/mail/polis/collections/set/sorted/todo/RedBlackTree.java
  test/ru/mail/polis/collections/AbstractICollectionTest.java
  test/ru/mail/polis/collections/MainTest.java
  test/ru/mail/polis/collections/TestAllTask.java
  test/ru/mail/polis/collections/TestExample.java
  test/ru/mail/polis/collections/TestHelper.java
  test/ru/mail/polis/collections/custom/Stub.java
  test/ru/mail/polis/collections/iterator/TestIntegerIncreasingSequencePeekingIterator.java
  test/ru/mail/polis/collections/iterator/TestMergingPeekingIncreasingIterator.java
  test/ru/mail/polis/collections/list/AbstractIDequeRemoveTest.java
  test/ru/mail/polis/collections/list/AbstractIDequeTest.java
  test/ru/mail/polis/collections/list/AbstractIQueueTest.java
  test/ru/mail/polis/collections/list/AbstractTestFullDeque.java
  test/ru/mail/polis/collections/list/TestFullDeque.java
  test/ru/mail/polis/collections/list/TestIDeque.java
  test/ru/mail/polis/collections/list/TestIDequeRemove.java
  test/ru/mail/polis/collections/list/TestIPriorityQueue.java
  test/ru/mail/polis/collections/list/TestIPriorityQueueBase.java
  test/ru/mail/polis/collections/list/TestIPriorityQueueComp.java
  test/ru/mail/polis/collections/list/TestIPriorityQueueRemove.java
  test/ru/mail/polis/collections/set/AbstractSetTest.java
  test/ru/mail/polis/collections/set/hash/BrokenStudent.java
  test/ru/mail/polis/collections/set/hash/TestHashTable.java
  test/ru/mail/polis/collections/set/hash/TestHastTableIteratorRemove.java
  test/ru/mail/polis/collections/set/sorted/AbstractTestBalancedSortedSet.java
  test/ru/mail/polis/collections/set/sorted/TestAVLTreeIterable.java
  test/ru/mail/polis/collections/set/sorted/TestAVLTreeIterableRemove.java
  test/ru/mail/polis/collections/set/sorted/TestBalancedSortedSet.java
  test/ru/mail/polis/collections/task/T10_AVL.java
  test/ru/mail/polis/collections/task/T11_AVLI.java
  test/ru/mail/polis/collections/task/T12_AVLIR.java
  test/ru/mail/polis/collections/task/T13_RBA.java
  test/ru/mail/polis/collections/task/T14_TBAR.java
  test/ru/mail/polis/collections/task/T15_OHT.java
  test/ru/mail/polis/collections/task/T16_OHTIR.java
  test/ru/mail/polis/collections/task/T1_ADS.java
  test/ru/mail/polis/collections/task/T2_ADSIR.java
  test/ru/mail/polis/collections/task/T3_ADF.java
  test/ru/mail/polis/collections/task/T4_LDS.java
  test/ru/mail/polis/collections/task/T5_LDSIR.java
  test/ru/mail/polis/collections/task/T6_LDF.java
  test/ru/mail/polis/collections/task/T7_APQS.java
  test/ru/mail/polis/collections/task/T8_APQSIR.java
  test/ru/mail/polis/collections/task/T9_MPII.java
Labels: duplicate, invalid
